FRON-13 Implement landing page
P3K-TEAM/frontend pull request #1
Opened 2020-11-05 00:45 UTC by MaliniakovaKarin

2020-11-05 20:36 UTC, OliverKanat requested changes, later dismissed

2020-11-05 20:36 UTC, OliverKanat commented on src/components/Navigation.vue
> +</script>
Add newline

2020-11-06 10:58 UTC, MCFreddie777 commented on src/components/Navigation.vue
> +</script>
Reason?

2020-11-06 11:01 UTC, MCFreddie777 commented
I'll store your images using GIT LFS.

2020-11-06 11:05 UTC, MCFreddie777 approved these changes
Looks good to me. Saw some nitpicks like bad formatting or unnecessary newlines, but we're format it altogether later. 

Keep the good work & feel free to merge! 👍

2020-11-06 12:30 UTC, merged