Fron 40 scroll to match on click in document compare
P3K-TEAM/frontend pull request #28
Opened 2021-03-28 16:15 UTC by Hemii

2021-03-28 18:42 UTC, DeMensa123 commented on src/views/DocumentCompare.vue
> +					<p  class="mx-auto">
please remove double space before class

2021-03-28 19:37 UTC, DeMensa123 approved these changes, later dismissed

2021-03-28 20:49 UTC, MCFreddie777 requested changes

2021-03-28 20:49 UTC, MCFreddie777 commented on src/views/DocumentCompare.vue
> +			id: 'A2',
unused variable

2021-03-28 20:49 UTC, MCFreddie777 commented on src/views/DocumentCompare.vue
> +					index: index
if key name and value is same, there's no need to do `index: index`, just `index`: is sufficient.

2021-03-29 18:40 UTC, MCFreddie777 approved these changes

2021-03-29 18:42 UTC, DeMensa123 approved these changes

2021-03-29 18:43 UTC, merged