FRON-48 GDPR approval
P3K-TEAM/frontend pull request #39
Opened 2021-04-19 15:19 UTC by MaliniakovaKarin

2021-04-19 16:32 UTC, MCFreddie777 submitted a review, later dismissed

2021-04-19 17:31 UTC, Hemii commented on src/views/Upload.vue
> +						</p>
Should we have these terms in English as well, if English is chosen ?

2021-04-20 12:40 UTC, MCFreddie777 requested changes
Don't forget about JIRA tags in commit messages.

2021-04-20 12:40 UTC, MCFreddie777 commented on src/i18n/languages/english.js
> +	emailPolicyTitle: '<h1 class="text-2xl font-bold">Conditions for the processing of personal data</h1>',
Please, do not add the html code to the translations. What if we wanted to changer the html tag or css classes? We would have to make it in both places.. What if we had thousands of language translations?

2021-04-20 12:40 UTC, MCFreddie777 commented on src/views/Upload.vue
> +					header: this.$i18n.t('emailPolicyTitle'),
Please, use string interpolation.

https://dmitripavlutin.com/string-interpolation-in-javascript/#:~:text=String%20interpolation%20is%20replacing%20placeholders,%24%7Bexpression%7D%20as%20a%20placeholder.


e.g.: 
```javascript
header: `<h1 class="text-2xl font-bold">${ this.$i18n.t('emailPolicyTitle') }</h1>`,
```

2021-04-20 17:28 UTC, MCFreddie777 approved these changes

2021-04-20 17:32 UTC, Hemii approved these changes

2021-04-20 19:25 UTC, merged